scrollbar_interactive yes
scrollbar_width 0.8
cursor_trail 1


font_family      JetBrains Mono
font_size        10.0
background_opacity 0.97
background #191c24

url_color #7689a7
url_style straight

input_delay 0
sync_to_monitor yes

